### ISSUE TITLE
Simple stencil fails with gtx86 backend

### ISSUE THREAD

**Issue by ofuhrer** [GridTools/gt4py#115]
The following stencil fails at compilation...
```Python
@gtscript.stencil
def stencil(f_in: gtscript.Field[float]):
    from __gtscript__ import computation, PARALLEL, interval
    with computation(PARALLEL), interval(...):
        tmp = 0.
```
...with...
```
In file included from .gt_cache/py36_1013/gtx86/__main__/m_example_def__gtx86_d14aad505f_pyext_BUILD/computation.cpp:3:0:
.gt_cache/py36_1013/gtx86/__main__/m_example_def__gtx86_d14aad505f_pyext_BUILD/computation.hpp:31:50: error: expected identifier before ')' token
 void run(const std::array<gt::uint_t, 3>& domain,);
```

**Comment by ofuhrer** [comment]
@tehrengruber Not sure if this should be disallowed. I think this would be worthy of a warning, but rest assured that the stencil above is exactly what I wanted to do.

**Comment by tehrengruber** [comment]
I simply disallowed it because the stencil is only legal if a domain is explicitly given and I wanted to avoid additional complexity in the stencil call for such a corner case. Now that I think about it there is however a valid use case for this, namely benchmarking the overhead of a stencil call. Is this also your use case?

**Comment by ofuhrer** [comment]
Yes. I was commenting out code to isolate a problem and then all of a sudden got this error.

**Comment by tehrengruber** [comment]
It is not legal since as of now the maximum domain is given by all *referenced* fields, which are none. Implementation-wise when no fields are referenced the maximum domain is the maximum index (e.g. 4294967295) resulting in an `std::bad_alloc` exception in the GridTools backend because of #103. It is however a valid question whether the maximum domain should depend on which fields are referenced or all fields. Both are valid perspectives, but maybe @gronerl can comment on this when he is available again. Reconsidering the benchmarking use case I would allow stencils without effect if the domain is given explicitly and we can still enable it for the implicit maximum domain if the semantics of it would change.

**Comment by havogt** [comment]
> but rest assured that the stencil above is exactly what I wanted to do.

What would you expect to happen? Would you expect more than a noop on calling that stencil? I don't think this should be valid code for measuring call overhead.

> Reconsidering the benchmarking use case I would allow stencils without effect if the domain is given explicitly and we can still enable it for the implicit maximum domain if the semantics of it would change.

I want to imply with my comment that there is no well-defined intuitive answer to what should happen. During optimization I'd expect that operations with no visible effect on program state should be eliminated and therefore it's unclear what you will measure with the code above. Maybe the call will never leave python, maybe all fields which are not referenced will get eliminated, maybe a CUDA kernel will be called, maybe not...

**Comment by havogt** [comment]
So my conclusion would be, an error is correct as there is no meaningful result that you can get from such a stencil.

**Comment by tehrengruber** [comment]
For optimizations enabled I agree, but when I disable them (no mechanism exists for this yet) the intuitive answer for me is that an empty stencil is generated and the generated code is called. So maybe to resolve this we could ask: If such a stencil is not allowed how should we benchmark the overhead?

**Comment by ofuhrer** [comment]
This conversation makes me smile. It feels a bit like we are saying that `a = 1. * b` is not allowed since it does not make sense, but `a = 2. * b` is. Let me explain...
```
@gtscript.stencil
def test(f_in: dtype, f_out: dtype)
    with computation(PARALLEL), interval(...):
        f_out = f_in
```
...seems reasonable. The following example is the one I actually have...
```
@gtscript.stencil
def test(f_in: dtype, f_out: dtype, flag: dtype_int)
    with computation(PARALLEL), interval(...):
        if flag:
            f_out = f_in
```
...which makes sense, but is actually is sometimes called with `flag = 0`, so nothing is actually done. Next up, the following...
@gtscript.stencil
def test(f_in: dtype, f_out: dtype)
    with computation(PARALLEL), interval(...):
        if __INLINE(flag):
            f_out = f_in
...should probably also work, even if `flag=False` at compile time. So finally, you are argueing that something like...
@gtscript.stencil
def test(f_in: dtype, f_out: dtype, flag: dtype_int)
    with computation(PARALLEL), interval(...):
        pass
```
...should not be allowed, and I struggle to understand why. ;-)

**Comment by havogt** [comment]
Let me explain my train of thoughts. My first reaction to this was, don't issue a warning, just do whatever the toolchain wants (as long as no visible state is changed). Expecting that this can be used for measuring launch overhead still doesn't make sense to me because it's also not well-defined which overhead you want to measure (launching into C++, with or without executing a CUDA kernel, etc.).
This first reaction comes from C++ and coincides with your `a = 1. * b` example. It's valid but the `1.` will be optimized away.
My second thought was, this is not a general purpose language, but a DSL that should help the user as much as possible to write what they want. The last example is not what the user wants. The 2 middle ones can be distinguished from the last without problem, the second to last could have an additional warning.

**Comment by ofuhrer** [comment]
Thanks for your reply. I see your point. I can for sure live with any decision here.

If you are interested in the discussion, here are some thoughts...
- I agree that measure overhead is ill-defined since you don't know what will be optimized away under the hood. A good DSL compiler will optimize everything away, and just implement this function in pure Python with a `pass`. Fact is, that is currently not the case and the toolchain is doing very little analysis and/or dead code removal.
- I actually am a user, and the last case is exactly what I wanted to do while working with the [sea-ice parametrization](https://github.com/VulcanClimateModeling/physics_standalone/blob/GT4Py/seaice/sea_ice_gt4py.py). I was measuring performance of Fortran vs. pure Python vs. gt4py implementations (see https://github.com/GridTools/gt4py/issues/102) and one thing that is striking is that there is much more runtime variance depending on the fraction of gridpoints where `flag = True` in the above simplified examples (runtime with all `flag = False` and all `flag = True` is almost the same). I wanted to remove all code with `if flag:` in order to check whether the runtime was dominated by the allocation and initialization of temporaries (last example above). So while I see your point that this is not a general purpose programming language, it still is a programming language and I think we should be careful about assumptions what the _user wants_ or the _user should do_ without actually gaining experience with actual users. Or otherwise put: It is a fine line between helping the user and patronizing the user.

**Comment by gronerl** [comment]
Independently of the discussion here, this is actually fixed in #59 (resolved by quietly accepting it / not generating a c++ extension at all). Now reading the discussion here I could be convinced that a warning would be more appropriate.

This example where you would just replace a field by a compile-time condition is There are more issues associated with replacing run-time conditionals with compile-time ones, such as:

For inlined (compile-time) conditionals, this would be valid:
```Python
@gtscript.stencil
def test(f_in: dtype, f_out: dtype)
    from __externals__ import flag
    with computation(PARALLEL), interval(...):
        if __INLINE(flag):
            B = f_in
            A = B[1, 1, 0]
```
The two assignments would have to end up in two different stages. 

However, 

```Python
@gtscript.stencil
def test(f_in: dtype, f_out: dtype, flag: dtype_int)
    from __externals__ import flag
    with computation(PARALLEL), interval(...):
        if flag:
            B = f_in
            A = B[1, 1, 0]
```
This would not be possible, since runtime conditionals have to go in a single stage, but this would cause a read-write conflict in `B`. Other cases can probably be constructed where this difference is more subtle, where e.g. the results would just be different. 

Maybe this issue is not the right place, but I think we should have some discussion about how to make these things a smooth experience.

**Comment by ofuhrer** [comment]
@gronerl Is there a fundamental reason why runtime conditionals have to go in a single stage, or is this simply a limitation of the current version of gt4py?

**Comment by gronerl** [comment]
The condition is point-wise, and everything that comes in the body of the if/else branch is then applied assuming the same grid point. Other resolutions would either incur some performance penalty or make the model even more complicated.

**Comment by ofuhrer** [comment]
I understand, I guess there are two use cases, one where the condition is actually point-wise (i.e. on a argument or temporary), or one where the condition is on a runtime scalar (same value for all gridpoints), e.g....
```Python
@gtscript.stencil
def test(f_in: dtype, f_out: dtype, *, dt: real):
    with computation(PARALLEL), interval(...):
        if dt > 0:
            tmp = f_in[1, 0, 0]
            f_out = -dt * (tmp[1, 0, 0] + tmp[-1, 0, 0])
        else:
            tmp = f_in[-1, 0, 0]
            f_out = dt * (tmp[1, 0, 0] + tmp[-1, 0, 0])
```

**Comment by tehrengruber** [comment]
I have updated the PR on this. The initial case is now covered and legal as long as the domain is explicitly specified, but a warning will be emitted.
