### ISSUE TITLE
next: unsupported negative floating point number casts

### ISSUE THREAD

**Issue by dastrm** [GridTools/gt4py#1643]
Using `-float(1)` anywhere within a field operator works, whereas `float(-1)` does not.

**Comment by tehrengruber** [comment]
This should be simple to add. The syntax `type_name(scalar_val)` is only implemented for literals, but `float(-1)` is actually a unary op on a literal, which is why it doesn't work. With GTIR the always somewhat artificial looking restriction that the argument has to be a literal is not required anymore anyway so we can fix this in one go.
