### ISSUE TITLE
Interface for inlining could be improved?

### ISSUE THREAD

**Issue by ofuhrer** [GridTools/gt4py#166]
The interface for specifying compile-time variables does not feel right. Currently we ask the user to specify `__INLINE()` around a variable to specify it as known at compile time, e.g. ...
```Python
@gtscript.stencil
def test(f_in: dtype, f_out: dtype)
    from __externals__ import flag
    with computation(PARALLEL), interval(...):
        if __INLINE(flag):
            B = f_in
            A = B[1, 1, 0]
```
There are several downsides to this:
- Saying `__INLINE` is exposes a technicality (the fact that we can remove the if-conditional). We should actually say something like `CONSTANT` or `COMPILE_TIME` instead.
- Changing a variable from  run-time to compile-time is tedious, since we have to go through the code and insert `__INLINE()` every time the variable is used. We should have a single place where we can easily define variables as being compile-time.

Possible solutions are to attach an attribute to the variables or to define a dictionary of compile-time variables that gt4py can query to check whether a variable is compile-time (similar to the JSON file that gtclang provides).

**Comment by jdahm** [comment]
If I recall correctly, anything that is not passed in as a parameter (or splitter in the case of regions) should be a compile time parameter. GT4Py should therefore be able to automatically detect if a conditional uses only compile-time variable references quite easily, and this can be removed.

**Comment by eddie-c-davis** [comment]
Agreed @jdahm, this possibility should definitely be explored as it makes the code much cleaner.

**Comment by egparedes** [comment]
I agree this should be improved but note that the current `_INLINE if` is actually completely different from a regular `if` because it works like a preprocessor macro. This not only means that the condition is evaluated at compile time, but also that it can be used anywhere in the code, not only inside a computation. The rationale for this behavior was that:
- it might be used as a very basic mechanism to define the control-flow part of the computation
- the different syntax makes explicit that the statements inside the `if` are executed each one of them with a individual parfor loop, which is completely different than statements inside a runtime if, where the parfor is outside the block

Once we agree in a definition of the parallel model for conditionals blocks which do not affect the execution of the statements inside the if branches, the second point of the previous list is clearly useless and the `INLINE`  could be removed. It's not hard to detect if the condition is compile-time or run-time, and it was actually done like that in previous versions, but we decided to add the different syntax because of the different behavior.

Regarding the first point, I see two options: either we add a different construct to express preprocessor-like conditionals (e.g. the `with CONDITION()` syntax in the GridTools/concepts#19) or we remove completely the preprocessor emulation and add a proper control-flow part to the stencils.

**Comment by jdahm** [comment]
We discussed this in a team meeting and the consensus was

1. that `__INLINE` is a terrible name that should be changed -- it feels like stencils are using some compiler internal to express something quite basic.
2. there should be a compiler pass that converts `if` conditions using only compile-time information to compile-time ifs automatically. Tracked in https://github.com/GridTools/gt4py/issues/1011.
