### ISSUE TITLE
Agree on function call semantics

### ISSUE THREAD

**Issue by mbianco** [GridTools/gt4py#199]
We need to define and describe how calling functions from GTScript code behaves in the context of the parallel model.

**Comment by jdahm** [comment]
I recently closed a related issue: https://github.com/GridTools/gt4py/issues/231.

**Comment by jdahm** [comment]
My proposal is a fairly simple semantic: the inputs are copied in the current context (only the IJ plane for the current vertical level if FORWARD or BACKWARD, otherwise on all levels), then statements are inlined such that all variables used in the function are unique temporaries (might be renamed), then return values are assigned.

cc: @twicki

**Comment by jdahm** [comment]
Agreed, the gtscript parallel model doesn't even mention 'function' 😮

**Comment by jdahm** [comment]
Moved to https://github.com/GridTools/concepts/issues/52.
