### ISSUE TITLE
Push off gtscript.function external symbol resolution time until stencil generation time

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#202]
In fv3core, for various reasons, we manually invoke `gtscript.stencil(definition=stencil_func, ...)` at the time of first usage, since we are still setting up the backend and rebuild flag at run-time in the tests. However, using externals that are defined later than module-load-time are not working, since `gtscript.function` tries to resolve the externals at load time.

I propose changing the decorator to register functions, and delay the symbol resolution until the time the stencil inlines the call.

**Comment by egparedes** [comment]
After thinking again about this and evaluating a possible implementation of this feature (#204), I'm not longer sure that this is needed. Regular explicit externals can be used inside functions too, which should solve the problem.

```python
# Example: constant is undefined at this point

@gtscript.function
def func(field_in):
    from __externals__ import constant

    return field_in + constant
```

**Comment by jdahm** [comment]
@egparedes Would you rather have a new function `gtscript.macro` or keyword argument e.g. `gtscript.function(delay=True)`?

**Comment by egparedes** [comment]
After some more discussions about this, we still think the best and most reliable way to have context-dependent compilation constants in production code would be to use explicit externals. Any compile-time optimization or check that you're doing right now should work exactly in the same way when using externals (otherwise, please open an issue).

If you want to keep using the current strategy, I think the best way to expose this feature of delaying the external resolution of the constants until the stencil compilation happens would be to keep the current behavior of `gt.function` but make the decorator optional for functions. When the stencil is compiled, if there are some callables which have not been marked earlier with a `gt.function` decorator, they should be processed at this time. This would be coherent with the current behavior ("globals are frozen when gt.decorators are applied") but at the same time will allow the delayed resolution of externals in functions as you want.

Example:

```
constant = 0

# gt.function ? -> if gt.function is applied here: constant == 0
def func(field_in):
    return field_in * constant

constant = 2.0

gt.stencil(...)
# If gt.function was applied to func, it will be used the value that was frozen at that time: constant == 0
# If func was not decorated, then it uses the same value that stencil sees: constant == 2.0
def stencil(field_in: gtscript.Field[float], field_out: gtscript.Field[float]):
    with computation(PARALLEL), interval(...):
        field_out = func(field_in) + constant

```

I guess the changes for the existing PR #204 would be minimal: keep `gt.function` as it is right now and, in the newly added code to annotate definitions during the stencil parsing,  change the triggering condition to finding a function/callable without annotations.
