### ISSUE TITLE
Remove PARALLEL keyword as iteration order

### ISSUE THREAD

**Issue by tehrengruber** [GridTools/gt4py#205]
The `PARALLEL` keyword used as vertical iteration order in the computation definition is often misunderstood by users. As decided in the syntax workshop the `PARALLEL` keyword should be removed and `computation()` should be defined as:

```python
def computation(iteration_order: Optional[IterationOrder] = None):
    pass
```
so it can be used with an empty `computation()`:
```python
with computation():  # Ok
    ...
```

During a transition period a deprecation warning should be printed.

**Comment by jdahm** [comment]
We discussed this in a team meeting and users seem to be put off by the proposal.

The feedback was that PARALLEL is like `const` in C++, it's useful because it's info the user is giving the compiler that it can use to determine if the user is making an error.

We now have a different proposal: keep the PARALLEL keyword as-is and also add an OIR optimization pass that converts FORWARD loops to PARALLEL if they can, and perhaps emit an info message saying the loop was converted.

I will open a new issue for that.
