### ISSUE TITLE
Field versus Storage

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#273]
GTScript uses the term "Field" for annotating storages, but uses "Storage" for the actual data. Is there an explanation for this, or should it be unified?

**Comment by egparedes** [comment]
`Field` is a concept of the GTScript DSL to represent data. `Storage` is an actual Python object which can be created and used outside of the DSL. It can be seen as one "implementation" of the Field concept in Python, but it's not the only one (in the new storage GDP this is more clear since any object implementing the "GT data protocol" will be accepted by a stencil object as a Field implementation).

**Comment by jdahm** [comment]
Thanks for the response! That makes sense. This question was brought up during the workshop, because users found it confusing. Hopefully with the storage GDP it will be clearer.
