### ISSUE TITLE
Importing `gtc:numpy` stencils import issues on Piz Daint

### ISSUE THREAD

**Issue by gronerl** [GridTools/gt4py#540]
Sometimes, when running `gtc:numpy`stencils on Piz Daint (SCRATCH), the follwoing type of error appears:

```
self = <gt4py.backend.gtc_backend.gtcnumpy.backend.GTCNumpyBackend object at 0x2aab22d95ac0>

    def _load(self) -> Type["StencilObject"]:
        stencil_class_name = self.builder.class_name
        file_name = str(self.builder.module_path)
        stencil_module = gt_utils.make_module_from_file(stencil_class_name, file_name)
>       stencil_class = getattr(stencil_module, stencil_class_name)
E       AttributeError: 'NoneType' object has no attribute 'two_optional_fields____gtcnumpy_412215ca76'

../src/gt4py/backend/base.py:268: AttributeError

```
however the member `two_optional_fields____gtcnumpy_412215ca76` is there. It seems to work after deleting the corresponding file from the cache and re-generating.

**Comment by havogt** [comment]
>however the member two_optional_fields____gtcnumpy_412215ca76 is there

Doesn't the error indicate that `stencil_module` is None and therefore something went wrong in `gt_utils.make_module_from_file(stencil_class_name, file_name)`?

**Comment by havogt** [comment]
Shouldn't we raise an exception here https://github.com/GridTools/gt4py/blob/eab01fa4adfeead8bcb2024283f371f937cf081e/src/gt4py/utils/base.py#L313?

**Comment by gronerl** [comment]
You're right. 

Yeah this is actually kind of annoying. It's been there since almost the beginning. @egparedes  Do you remember why we ignore exceptions here?

**Comment by egparedes** [comment]
Yeah, there were a reason for that `try-except` in `make_module_from_file`, but I don't remember...

In any case, returning `None` from `make_module_from_file` has the same meaning of raising an exception and thus `_load` should have checked that the value is not `None` and later decide what to do. It should also be possible to check what was wrong in `make_module_from_file` because the silenced exception should have been printed.

For a future-proof solution, either we always raise exceptions in `make_module_from_file` or we could add a `raise_exceptions` keyword argument in `make_module_from_file` to let the caller set the behavior regarding exceptions (default value should be `False` for backward compatibility or `True` if we want to be strict).

**Comment by gronerl** [comment]
Yes, sorry, the printed error is that there is no such module (i.e. no `m_computation_*` which gtc:numpy creates and puts the actual computations in.) However it is there after the crash. Probably a file system problem, but maybe there's a way to make our code handle this, like introducing a wait for the file to exist.

**Comment by egparedes** [comment]
Yes, that's certainly possible. In `_load` we could retry a certain number of times with a certain delay between tries. Both options could be configurable with specific entries in `config.cache_settings`, for example `load_retries`, `load_retry_delay` (where `load_retry_delay` should be expressed in milliseconds and it could be either a number or a tuple of numbers such as `len(load_retry_delay) == load_retries`)
