### ISSUE TITLE
Unexpected behaviour of nested subroutines with vertical data dependencies

### ISSUE THREAD

**Issue by DropD** [GridTools/gt4py#56]
Results differ for the same calculation done in a subroutine depending on whether it is called by the stencil directly or through another subroutine.

The attached ipython notebook illustrates the problem:

[nested_subroutines_with_data_dependencies.ipynb.zip](https://github.com/GridTools/gt4py/files/4912326/nested_subroutines_with_data_dependencies.ipynb.zip)

**Comment by jdahm** [comment]
I believe your example fails for the same reason https://github.com/GridTools/gt4py/issues/231 does. `copy_forward` and `a_b_forward` assume that the temporary inside the function call is copied over vertical levels other than the current one.

**Comment by jdahm** [comment]
@tehrengruber I believe the follow-on task here is to raise an error in the frontend if, inside a FORWARD or BACKWARD context, a vertical offset is used in a function call, since that is not copied. Should we make a new issue for that?

In the future we can remove that error if we add a semantic to copy the whole vertical, or whatever levels are needed (harder to determine).

**Comment by jdahm** [comment]
I'm going to close this for now, feel free to re-open if we think this is a problem.
