### ISSUE TITLE
Summary of legal array bounds

### ISSUE THREAD

**Issue by havogt** [GridTools/gt4py#596]
This is to address problems in #582, #568 and discuss legal array bounds in general.
We (@tehrengruber, @egparedes, @havogt) came to the conclusion that the we can apply the following simple rule:

**Execution of a program is legal if all accesses in all branches are within array bounds.**

This means:
- [ ] the first example of #568 is not legal, the access in k need to be protected by an interval or the size of the array has to be increased such that the problematic access is not out-of-bounds.
- [ ] the example of #582 is legal if `field_in` is at least one k-layer larger than the domain of the computation
- [ ] creating a field with negative origin (origin is out-of-bounds) is legal as long as all accesses in computations are within array bounds.

If you see problems with this rule, especially for optimizations, let us know.

**Comment by leuty** [comment]
These "illegal" offsets often relate to interactions with lateral and lower/upper boundary conditions. While these cases can indeed be treated by splitting the computation intervals accordingly, doing so can be cumbersome for more complicated stencils. It thus may be worthwhile to think about functionality that generates specialized cases for BCs, in particular since boundary conditions are ubiquitous and highly structured.

**Comment by gronerl** [comment]
Should this go into the concepts repo?

**Comment by havogt** [comment]
https://github.com/GridTools/concepts/pull/54 Needs to be moved back to the docs

**Comment by havogt** [comment]
added to doc
