### ISSUE TITLE
dace-webclient commit-specific automatic installation causes issues with JupyterLab 3.3.0

### ISSUE THREAD

**Issue by jbaksta** [GridTools/gt4py#686]
I've got a user who is wanting to leverage gt4py, but upon reviewing with others, have noticed an issue with dace-webclient that will manifest itself by breaking the JavaScript DOM, particularly `class Node`. While this is more of a dace issue and may be remediated, when installing dace gt4py pulls in a specific commit and therefore probably won't pick up the fix it. dace-webclient doesn't have a `class Node` in the current HEAD; perhaps it's already fixed upstream.

So this is more of a FYI. The issue comes up if I run the `demo_burgers.ipynb` example, but once that JavaScript from dace is leaked, then other odd things like this happen beyond the scope of even the current notebook such as an independent console:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/2792834/157080610-6f00d917-8eef-43b3-b8c4-283ca8c3e520.png">

You can see the two other issues here:
. jupyterlab/jupyterlab#12139
. spcl/dace-webclient#70

**Comment by jdahm** [comment]
@jbaksta - Thanks for letting us know.

It's our goal to minimize the required dependency surface of gt4py, so hopefully soon dace won't be required to be installed alongside gt4py. That's tracked in https://github.com/GridTools/gt4py/issues/594.

> If I replace the commit in setup.cfg with a no reference to a commit and true up the examples/demo_burgers.ipynb, then I'm fairly certain it works properly, but unsure what additional side effects this has on the rest of the package here.

I believe later commits should be fine, but you're right to be skeptical since we are not testing with them yet. If you'd like you can open a PR to the gt4py master branch that updates the dace version, and we can check if it works!

**Comment by havogt** [comment]
The current release version of dace doesn't work with master if you would like to use the dace. We should update as soon as possible and get #594 in.
