### ISSUE TITLE
Possibly move __call__ method into StencilObject base class

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#984]
None of the backend classes override `generate_pre_run` or `generate_post_run`, so there is no reason other than argument typing for it to be in the base class.

**Comment by gronerl** [comment]
The `__call__` of StencilObjects is code generated and contains the specific field names in the signature that are declared in the stencil. They can not be moved to the base class equivalently. 

On the other hand,  `generate_pre_run` and `generate_post_run` are methods in code generation, not run time. Are you referring to the generaters rather than the `StencilObject` here?

**Comment by jdahm** [comment]
> The __call__ of StencilObjects is code generated and contains the specific field names in the signature that are declared in the stencil. They can not be moved to the base class equivalently.

Sorry I wasn't clear. I thought it could just be `__call__(*args, **kwargs)` and forwarded to the stencil. However, when thinking about this more I think you've convinced me that this function signature correctness is important enough to have the code generate it.
